tests/fixtures/definitely-typed-types, tests/test_no_hang.js
I want to make sure that the parser doesn't hang on complex typescript types.
Gathered by walking the syntax tree for all the typescript files in Definitely Typed and printing the type nodes. 3700 unique types seems low for Definitely Typed, with 5800 packages, so it's likely that I missed some. I'll expand this list later.
=> Add no-hang test for Definitely Typed types

.eslintignore, .jscsrc
This makes linters ignore the `peg_lib` directory.
=> fix(eslint): Ignore `peg_lib` directory

lib/publishing.js, tests/test_publishing.js
- Breaking change: Have GENERIC publisher publish with a dot when `ANGLE_BRACKET_WITH_DOT` is present (not only legacy Closure but also used in jsdoc)
The main syntax specified at https://jsdoc.app/tags-type.html for bracketed types appears to be with a dot, so this PR changes the publishing behavior to express it. While we could use a custom publisher over at eslint-plugin-jsdoc (which is impacted in its `check-types` fixer which does not preserve the user's dot notation), I figured this made sense as a default, but thought I'd check with anyone else who might have an opinion (e.g., @Kuniwak, @sandersn , @gajus ).
FWIW, I also pushed some non-breaking refactoring changes (mostly using ES6 as supported by our targeted Node `engines` (>= 6)).
=> Publishing change for angle bracket with dot

.editorconfig
This adds an [EditorConfig] file, so that the project’s indentation style is maintained without needing to reconfigure the editor.
[EditorConfig]: https://editorconfig.org
=> chore: Add `.editorconfig`

README.md, lib/traversing.js, tests/test_traversing.js
Ok, here's that other PR I wanted to get in...
For `check-types` in `eslint-plugin-jsdoc`, we're now allowing replacement or error reporting for types based on whether they are parents are children (e.g., one might accept `Array.<string>` but not just `Array` (or vice versa).
We need something like this PR to do that properly.
This PR will:
1. Pass ~`undefined`~ (*now `null`*) for parent name and type if there is no parent (at root).
2. Pass the most immediate available parent name and ~type~ (*now the parent node*).
`eslint-plugin-jsdoc` can thus do such as ignore `Array` if it has the parent name `subject` (and thus has children), and report it otherwise.
~To be more sure this will fully work, I should really fully implement my `eslint-plugin-jsdoc` fixes against this branch, but wanted …
=> feat(traversal): pass on immediate parent property name and type

README.md, lib/publishing.js, peg_lib/jsdoctype.js, peg_src/jsdoctype.pegjs, tests/test_parsing.js, tests/test_publishing.js, tests/test_traversing.js
- Fix/Enhancement: Preserve quote style information (single or double) for strings from parsing to publishing
- Fix: In parsing/grammar, strip extra backslashes in strings for results; these serve as backslash escapes within a string  (had already added them for publishing)
- Testing: Add parsing tests that throw for unescaped quotes in strings; add publishing tests for odd/even backslashes in strings
- Testing: Add tests for single quote string
(Builds on 1a7dbc7c5373dc31b3d24afd8bd684e5b9902573 and e31fea3f2db0c77a05ca68c61cc063eea798865d which I added to `master` as small fixes before realizing I needed some additional work as presented in this PR.)
~I hope to also add similar fixes to allow similar fixes related to quotes and backslashes within `MemberName`.~ *(Now in PR #71)*
=> Allow preserve of string quote style; fixes for quotes and backslashes in strings

README.md, lib/publishing.js, peg_lib/jsdoctype.js, peg_src/jsdoctype.pegjs, tests/test_parsing.js
~I built this on top of #70, so you may want to review that first, and then I can rebase this as necessary.~ *Done*
- Fix/enhancement: Support preserving quote style of `MemberName` in parsing and publishing
- Fix: Disallow unescaped backslash before quote in `MemberName` (fixes #69)
- Testing: Add tests for backslashes and quotes within `MemberName`
~I apologize for the good number of changes in the test files, but I was finding the lack of a hierarchy hard to navigate, so I grouped them or grouped them further (Mocha `describe`). I'm confident there should have been no copy-paste errors;~ *Removed from this PR.*
~I was motivated to add a few other tests though not related to `MemberName` (arrow functions and single quote strings) as I was doing the reorganization.~ *Added to `master` …
=> Member names and quotes/backslashes; misc. test additions/refactoring

package-lock.json, package.json, peg_src/jsdoctype.pegjs, tests/test_parsing.js, tests/test_publishing.js, tests/test_traversing.js
Builds on #70 and #71 .
Makes the tests hierarchical with Mocha `describe` statements and regroupings.
=> Tests hierarchical

index.js, lib/parsing.js, package-lock.json, package.json, peg_src/jsdoctype.pegjs, tests/test_index.js, tests/test_parsing.js, tests/test_publishing.js, tests/test_traversing.js
Builds on #72 .
BREAKING CHANGE: Rename exported `SyntaxError` to `JSDocTypeSyntaxError` to avoid shadowing upon destructuring (fixes #67)
=> Syntax error

lib/publishing.js, peg_lib/jsdoctype.js, peg_src/jsdoctype.pegjs, tests/test_parsing.js, tests/test_publishing.js
- fix: disallow backslash in `RecordTypeExprEntryKey` when not paired to be followed by a non-quote character
- fix: tighten unquoted `RecordTypeExprEntryKey` to disallow numbers followed by non-numbers (except as part of a decimal and/or scientific notation)
- fix: allow optional `+` at beginning of decimal literals and optional `e` scientific notation at end (at least TypeScript allows in `RecordTypeExprEntryKey` and presumably elsewhere decimal literals are allowed)
- feat: Preserve quote style for `RecordTypeExprEntryKey`
Note that the change to `DecimalNumberLiteralExpr` impacts `NumberLiteralExpr` which impacts `ValueExpr` which impacts many types up to the top: (`UnionTypeExprOperand`, `PrefixUnaryUnionTypeExprOperand`, `KeyQueryExprOperand`, `SuffixUnaryUnionTypeExprOperand`, …
=> Backslash record type expression entry key

.eslintignore, lib/publishing.js, peg_lib/jsdoctype.js, peg_src/jsdoctype.pegjs, tests/test_parsing.js, tests/test_publishing.js
Builds on #78
- fix: allow quotes in `FilePathExpr` (for `module:"..."`)
- feat: preserve quote style for `FilePathExpr`
- chore: remove unused item in `.eslintignore`
Addresses the `module:"..."` part of #58.
=> File path quoted

lib/traversing.js, package-lock.json, package.json, tests/test_traversing.js
fix(traversal): external no longer traverses name node children (it includes the `name` and `quoteStyle` directly)
=> Fix for traversal with `external`

lib/SyntaxType.js, lib/publishing.js, peg_lib/jsdoctype.js, peg_src/jsdoctype.pegjs, tests/fixtures/typescript-types, tests/test_parsing.js, tests/test_publishing.js
Typescript says this about optional keys in the object literal type:
```javascript
/**
* @type {{ a: string, b: number= }}
*/
var wrong;
/**
* Use postfix question on the property name instead:
* @type {{ a: string, b?: number }}
*/
var right;
```
This can be seen on: https://www.typescriptlang.org/docs/handbook/type-checking-javascript-files.html#patterns-that-are-known-not-to-be-supported
Previously only way to define an optional key was through a parameter on the type of that key, but as can be seen that isn't supported by TypeScript currently, they rather prefer to have
the key suffixed by a `?`, something that this commit adds support for.
Related discussions in the Closure project, which has not arrived at a conclusion yet: https://github.com/google/closure-compiler/issues/126
=> Parse TypeScript style optional keys

index.js, lib/parsing.js, lib/publishing.js
As a follow up to #84 I thought it could be nifty to actually add a full type definition for the AST nodes.
It can probably be much improved, but this was a first quick stab at it.
=> Add a full type definition for the AST nodes

package.json, tests/test_no_syntax_error.js, tests/test_syntax_error.js, tests/utils.js
This creates a new `it(…)` context per fixture, so that syntax errors in one fixture don’t prevent syntax errors in another fixture from being reported.
I had this sitting around since developing #88.
=> test(no‑syntax‑error): Improve error messages when parsing fails

lib/publishing.js, peg_lib/jsdoctype.js, peg_src/jsdoctype.pegjs, tests/test_parsing.js, tests/test_traversing.js
Though this is a breaking change, I think it is worth it to provide consistency in traversal (and this particular node type hasn't been supported very long anyways).
I think this makes more sense than fixing things at our eslint-plugin-jsdoc level (as per this PR: https://github.com/gajus/eslint-plugin-jsdoc/pull/419 ).
=> Empty variadic any

lib/traversing.js, tests/test_traversing.js
fix: for traversal, change the expected `new` on arrow from a node to a string; fixes #103
=> traversal: change expected `new` on arrow from a node to a string

.eslintignore, .gitignore, .npmignore, package-lock.json, package.json
This isn't needed for that npm release, but thought I'd file now as a PR to make sure folks were happy with this approach.
FWIW, there are issues filed of pegjs for code coverage ([just added](https://github.com/pegjs/pegjs/issues/631)) and for a prerequisite of this, [source maps](https://github.com/pegjs/pegjs/issues/93), but I think it is still worth adding `nyc` here now in this PR, as it still allows us to detect coverage for the non-PEG files (and if someone really wanted, they could dig into the compiled PEG file so as to compare manually back to PEG source).
Once this may be merged, I have a couple coverage tests/changes we can add to improve coverage.
=> testing: add code coverage

lib/publishing.js, peg_lib/jsdoctype-closure.js, peg_lib/jsdoctype-jsdoc.js, peg_lib/jsdoctype-permissive.js, peg_lib/jsdoctype-typescript.js, peg_src/jsdoctype.pegjs, tests/test_parsing.js, tests/test_publishing.js, tests/test_traversing.js
fix: insist on whitespace after keywords "typeof" and "keyof"
=> Whitespace after keywords

lib/parsing.js, package.json, peg_lib/jsdoctype-closure.js, peg_lib/jsdoctype-jsdoc.js, peg_lib/jsdoctype-permissive.js, peg_lib/jsdoctype-typescript.js, tests/test_parsing.js
Builds on #115.
feat: alllow `startRule` option to validate only namepaths; fixes #86
This will allow `valid-types` in `eslint-plugin-jsdoc` to more narrowly focus on insisting that namepaths be used and not merely any types.
=> Start rule (namepaths)

index.js
Realized our demo will need these...
(This is probably more of a bug for missing these in the exports than a feature, but it wasn't exactly broken either.)
=> Export mode-specific SyntaxError's

.travis.yml, package-lock.json, package.json
Following the instructions from https://github.com/semantic-release/semantic-release/blob/master/docs/usage/getting-started.md#getting-started , I think **before merging this**, we need to add the following items as environmental variables at https://travis-ci.org/github/jsdoctypeparser/jsdoctypeparser/settings :
- `GH_TOKEN` (a Github personal access token [created](https://github.com/settings/tokens/new) with the `public_repo` scope)
- `NPM_TOKEN` (created via [npmjs.com or `npm token create`](https://docs.npmjs.com/creating-and-viewing-authentication-tokens))
I have tokens ready and could add them if you wanted me to take care of it, but since I don't believe I have npm publish access (puzzingly, `npm owner ls` only shows `orgachem` and no one else, not even @sandersn ), so my token …
=> Semantic release
